version: "3.8"

services:
  backend:
    image: snir1551/backend:${BACKEND_TAG}
    command: npm start
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

  frontend:
    image: snir1551/frontend:${FRONTEND_TAG}
    command: npm start
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  mongo:
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}" 
