version: "3.8"

services:
  backend:
    command: npm start
    ports:
      - "8080:8080" 

  frontend:
    command: npm start
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  mongo:
    ports:
      - "27017:27017"  
