version: "3.8"

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - appnet


  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - appnet

volumes:
  mongo-data:


networks:
  appnet:
    driver: bridge
