name: CI/CD Pipeline

on:
  # push:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
        environment:
          description: "Choose environment"
          required: true
          default: dev
          type: choice
          options:
            - dev
            - prod



jobs:

  frontend-tests:
    uses: ./.github/workflows/frontend-test.yml
  
  backend-tests:
    uses: ./.github/workflows/backend-test.yml

  docker-up:
    if: ${{ inputs.environment == 'dev' }}
    needs: [frontend-tests, backend-tests]
    uses: ./.github/workflows/build.yml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}
    secrets: inherit

  # push-images:
  #   needs: [backend-tests, frontend-tests]
  #   uses: ./.github/workflows/push-to-dockerhub.yml
  #   with:
  #     environment: ${{ github.event.inputs.environment }}
  #   secrets: inherit

  notify:
    needs: [backend-tests, frontend-tests]
    if: always()
    uses: ./.github/workflows/notify.yml
    with:
      job_start_time: ${{ needs.frontend-tests.outputs.job_start_time }}
      backend_test_status: ${{ needs.backend-tests.result }}
      frontend_test_status: ${{ needs.frontend-tests.result }}
      backend_health: ${{ needs.docker-up.outputs.backend_health }}
      frontend_health: ${{ needs.docker-up.outputs.frontend_health }}
    secrets: inherit


  terraform-remote-state-initialization:
    uses: ./.github/workflows/terraform-remote-state-initialization.yml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}
    secrets: inherit

  deploy-infrastructure:
    needs: [terraform-remote-state-initialization]
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}
    secrets: inherit

  deploy-app:
    if: ${{ inputs.environment == 'dev' }}
    needs: [deploy-infrastructure]
    uses: ./.github/workflows/deploy-app.yml
    with:
      vm_ip: ${{ needs.deploy-infrastructure.outputs.vm_ip }}
      environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}
    secrets: inherit


  # deploy-prod:
  #   if: ${{ inputs.environment == 'prod' }}
  #   needs: [deploy-infrastructure, push-images]
  #   uses: ./.github/workflows/deploy-prod.yml
  #   with:
  #     vm_ip: ${{ needs.deploy-infrastructure.outputs.vm_ip }}
  #     environment: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'dev' }}
  #     frontend_tag: ${{ needs.push-images.outputs.frontend_tag }}
  #     backend_tag: ${{ needs.push-images.outputs.backend_tag }}
  #   secrets: inherit

  reboot-vm:
    needs: [deploy-infrastructure, deploy-app]
    uses: ./.github/workflows/reboot-vm.yml
    with:
      vm_ip: ${{ needs.deploy-infrastructure.outputs.vm_ip }}
    secrets: inherit

  post-reboot-healthcheck:
    needs: [deploy-infrastructure, reboot-vm]
    uses: ./.github/workflows/post-reboot-healthcheck.yml
    with:
      vm_ip: ${{ needs.deploy-infrastructure.outputs.vm_ip }}
    secrets: inherit

  final-notify:
    needs: [deploy-infrastructure, post-reboot-healthcheck]
    uses: ./.github/workflows/final-notify.yml
    with:
      vm_ip: ${{ needs.deploy-infrastructure.outputs.vm_ip }}
    secrets: inherit

  # update-deployment-log:
  #   needs: post-reboot-healthcheck
  #   uses: ./.github/workflows/commit-deployment-log-task9.yml
