name: Frontend Test

on:
  workflow_dispatch: # Can be run manually
  workflow_call:
    outputs:
      job_start_time:
        description: "Start timestamp"
        value: ${{ jobs.test.outputs.job_start_time }}

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18, 20, 22]
    outputs:
      job_start_time: ${{ steps.set_time.outputs.job_start_time }}

    defaults:
      run:
        working-directory: app/frontend

    steps:
      - uses: actions/checkout@v3

      - id: set_time
        run: echo "job_start_time=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: app/frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Install ESLint
        run: npm install -g eslint

      - name: Run ESLint
        run: npx eslint .

      - name: Serve frontend for testing
        run: |
          npm start &
          sleep 3
          curl -I http://localhost:3000
