name: Notify Status

on:
  workflow_call:
    inputs:
      job_start_time:
        required: true
        type: string
      backend_test_status:
        required: true
        type: string
      frontend_test_status:
        required: true
        type: string
      backend_health:
        required: true
        type: string
      frontend_health:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      - name: Calculate job duration
        id: calc
        run: |
          END_TIME=$(date +%s)
          DURATION=$(( END_TIME - ${{ inputs.job_start_time }} ))
          echo "duration=${DURATION}s" >> $GITHUB_OUTPUT

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "*CI/CD Pipeline - *\n\n* Duration:* `${{ steps.calc.outputs.duration }}`\n\n* Backend Test:* `${{ inputs.backend_test_status }}`\n* Frontend Test:* `${{ inputs.frontend_test_status }}`\n\n* Backend Health:* `${{ inputs.backend_health }}`\n* Frontend Health:* `${{ inputs.frontend_health }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
