name: Open Required Ports Task9

on:
  workflow_call:
  workflow_dispatch:

jobs:
  open-ports:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set variables
        run: |
          echo "RESOURCE_GROUP=mtc-resources" >> $GITHUB_ENV
          echo "NSG_NAME=mtc-nsg" >> $GITHUB_ENV

      - name: Open port 3000 (frontend)
        run: |
          echo "Checking if rule Allow-Port-3000 exists..."
          if ! az network nsg rule show \
            --resource-group $RESOURCE_GROUP \
            --nsg-name $NSG_NAME \
            --name Allow-Port-3000 &>/dev/null; then
            echo "Creating rule to allow port 3000"
            az network nsg rule create \
              --resource-group $RESOURCE_GROUP \
              --nsg-name $NSG_NAME \
              --name Allow-Port-3000 \
              --priority 101 \
              --destination-port-ranges 3000 \
              --direction Inbound \
              --access Allow \
              --protocol Tcp \
              --source-address-prefixes '*' \
              --destination-address-prefixes '*'
          else
            echo "Rule already exists."
          fi

      - name: Open port 8080 (backend)
        run: |
          echo "Checking if rule Allow-Port-8080 exists..."
          if ! az network nsg rule show \
            --resource-group $RESOURCE_GROUP \
            --nsg-name $NSG_NAME \
            --name Allow-Port-8080 &>/dev/null; then
            echo "Creating rule to allow port 8080"
            az network nsg rule create \
              --resource-group $RESOURCE_GROUP \
              --nsg-name $NSG_NAME \
              --name Allow-Port-8080 \
              --priority 102 \
              --destination-port-ranges 8080 \
              --direction Inbound \
              --access Allow \
              --protocol Tcp \
              --source-address-prefixes '*' \
              --destination-address-prefixes '*'
          else
            echo "Rule already exists."
          fi
